-- = LISTAR TODO
DELIMITER $$
CREATE PROCEDURE PROC_CATEGORIA_LISTAR()
BEGIN
  SELECT * FROM CATEGORIA;
END $$
DELIMITER ;



-- = CREAR O MODIFICAR
DELIMITER $$
CREATE PROCEDURE PROC_CATEGORIA_CU(
    _ID_CATEGORIA INT,
    _NOM_CATEGORIA VARCHAR(30)
) BEGIN
    -- MENSAJE A LA INTERFAZ
    DECLARE __ICON VARCHAR(10) DEFAULT 'error';
    DECLARE __MESSAGE_TEXT VARCHAR(300) DEFAULT 'HA OCURRIDO UN ERROR';
    DECLARE __STATUS_CODE CHAR(3) DEFAULT '501';

    -- COMPROBAR QUE EL NOMBRE NO EXISTA
    DECLARE __EXISTS_NOMBRE INT DEFAULT 0;
    SELECT ID_CATEGORIA INTO __EXISTS_NOMBRE
    FROM CATEGORIA
    WHERE ID_CATEGORIA <> _ID_CATEGORIA AND
    NOM_CATEGORIA = _NOM_CATEGORIA AND ESTADO <> 0;


    IF __EXISTS_NOMBRE = 0 THEN
        IF _ID_CATEGORIA = 0 THEN
            INSERT INTO CATEGORIA
                (NOM_CATEGORIA, ESTADO) VALUES
                (_NOM_CATEGORIA, '1');

                -- MENSAJE
                SET __ICON = 'success';
                SET __MESSAGE_TEXT = 'REGISTRO EXITOSO';
                SET __STATUS_CODE = '201';
        ELSE
            UPDATE CATEGORIA
                SET 
                    NOM_CATEGORIA = _NOM_CATEGORIA
                WHERE
                    ID_CATEGORIA = _ID_CATEGORIA;

                -- MENSAJE
                SET __ICON = 'success';
                SET __MESSAGE_TEXT = 'DATOS ACTUALIZADOS';
                SET __STATUS_CODE = '202';
        END IF;
    ELSE
         -- MENSAJE
        SET __ICON = 'warning';
        SET __MESSAGE_TEXT = '¡EL NOMBRE YA SE ENCUENTRA EN USO!';
        SET __STATUS_CODE = '200';
    END IF;
    SELECT __ICON AS 'ICON', __MESSAGE_TEXT AS 'MESSAGE_TEXT', __STATUS_CODE AS 'STATUS_CODE';
END $$
DELIMITER ;



-- = ELIMINAR CATEGORIA
DELIMITER $$
CREATE PROCEDURE PROC_CATEGORIA_DELETE(
    _ID_CATEGORIA INT
) BEGIN
    -- MENSAJES A LA INTERFAZ
    DECLARE __ICON VARCHAR(10) DEFAULT 'error';
    DECLARE __MESSAGE_TEXT VARCHAR(300) DEFAULT 'HA OCURRIDO UN ERROR';
    DECLARE __STATUS_CODE CHAR(3) DEFAULT '501';

    -- SABER SI NO SE ENCUENTRA O YA ESTA ELIMINADO
    DECLARE __NO_EXISTS INT DEFAULT 0;

    SELECT IF(ESTADO <> 0, ID_CATEGORIA, 0) INTO __NO_EXISTS FROM CATEGORIA
    WHERE ID_CATEGORIA = _ID_CATEGORIA;

    IF __NO_EXISTS = 0 THEN 
        -- MENSAJE
        SET __ICON = 'warning';
        SET __MESSAGE_TEXT = 'EL ELEMENTO NO EXISTE O YA HA SIDO ELIMINADO';
        SET __STATUS_CODE = '200';
    ELSE
        UPDATE CATEGORIA
            SET ESTADO = '0'
            WHERE ID_CATEGORIA = _ID_CATEGORIA;
        -- MENSAJE
            SET __ICON = 'success';
            SET __MESSAGE_TEXT = 'ELEMENTO ELIMINADO';
            SET __STATUS_CODE = '202';
    END IF;
    SELECT __ICON AS 'ICON', __MESSAGE_TEXT AS 'MESSAGE_TEXT', __STATUS_CODE AS 'STATUS_CODE';
END $$
DELIMITER ;