-- = SELECT PRIVILEGIO
DELIMITER //
CREATE PROCEDURE PROC_SELECT_PRIVILEGIO()
BEGIN
    SELECT * FROM privilegio WHERE ESTADO = '1';
END //

DELIMITER ;

-- = SELECT CATEGORIA
DELIMITER //
CREATE PROCEDURE PROC_SELECT_CATEGORIA()
BEGIN
    SELECT * FROM CATEGORIA WHERE ESTADO = '1';
END //

DELIMITER ;


-- = SELECT CATEGORIA
DELIMITER //
CREATE PROCEDURE PROC_SELECT_TIPO_VEHICULO()
BEGIN
    SELECT * FROM TIPO_VEHICULO WHERE ESTADO = '1';
END //

DELIMITER ;



-- = SELECT SEGURIDAD
DELIMITER //

CREATE PROCEDURE PROC_SELECT_SEGURIDAD()
BEGIN
    SELECT P.*
    FROM PERSONA P
    INNER JOIN SEGURIDAD S ON P.ID_PERSONA = S.ID_PERSONA
    WHERE S.ESTADO = '1';
END //

DELIMITER ;

